# Generated by Django 6.0.3 on 2026-04-23 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0017_alter_agentprofile_options_alter_prompt_category'),
        ('scene', '0042_remove_userprofile_google_api_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='voice',
            new_name='audio_voice',
        ),
        migrations.AddField(
            model_name='character',
            name='voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='agent.voice'),
        ),
        migrations.AddField(
            model_name='scene',
            name='voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenes', to='agent.voice'),
        ),
    ]
