# Generated by Django 6.0.3 on 2026-04-24 03:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0044_alter_storyprofile_user_storygroup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storygroup',
            name='users',
            field=models.ManyToManyField(related_name='story_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
