# Generated by Django 6.0.3 on 2026-04-25 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0045_storygroup_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='exec_on_save',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='exec_on_save',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='exec_on_save',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='prop',
            old_name='exec_on_save',
            new_name='action',
        ),
    ]
