# Generated by Django 6.0.3 on 2026-04-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0016_alter_agentprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentprofile',
            options={'verbose_name': 'AI User Profile', 'verbose_name_plural': 'AI User Profiles'},
        ),
        migrations.AlterField(
            model_name='prompt',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('refine', 'Refine'), ('video_image', 'Video'), ('video_first_last', 'Video First Last'), ('comic', 'Comic'), ('comic', 'Comic')], default='general', max_length=100),
        ),
    ]
