# Generated by Django 6.0.4 on 2026-05-04 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0016_alter_agentprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentprofile',
            options={'verbose_name': 'AI User Profile', 'verbose_name_plural': 'AI User Profiles'},
        ),
    ]
