# Generated by Django 6.0.3 on 2026-05-03 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0018_alter_prompt_category_chatmessage'),
        ('scene', '0046_rename_exec_on_save_action_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Game', max_length=100)),
                ('prompt', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_duration', models.DurationField(blank=True, help_text='Duration of each turn. After this time, the turn will be automatically finished. Format: HH:MM:SS (e.g. 00:30:00 for 30 minutes)', null=True)),
                ('state', models.CharField(choices=[('created', 'Created'), ('ready', 'Ready'), ('scene', 'Hints'), ('plot', 'Plots'), ('finished', 'Finished')], default='ready', max_length=100)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.agent')),
                ('group', models.ForeignKey(blank=True, help_text='If the invitation is accepted the user will also be added to this group. You can generate invitations for group members automatically', null=True, on_delete=django.db.models.deletion.CASCADE, to='scene.storygroup')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scene.story')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brainrain.storygame')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brainrain.gamesession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('scene', 'Add Scene'), ('plot', 'Plots'), ('help', 'Help')], default='scene', max_length=100)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.agent')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brainrain.player')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='brainrain.gamesession')),
            ],
        ),
    ]
