# Generated by Django 6.0.3 on 2026-05-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainrain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turn',
            name='finished',
        ),
        migrations.AddField(
            model_name='turn',
            name='pass_turn',
            field=models.BooleanField(default=False, help_text='If true, the turn will be passed to the next player'),
        ),
        migrations.AddField(
            model_name='turn',
            name='prompt_refine',
            field=models.TextField(blank=True, null=True),
        ),
    ]
